# Site settings
title: Đạt Nguyễn
description: All about Nguyễn!
bio: >
  Hi, I'm Dat Nguyen.
  I'm passionate about creating awesome products that help plenty of people improving their lives.
url: 'https://datnguyen12345.github.io/'
blog_url: 'https://datnguyen12345.github.io/'
baseurl:

author:
  name: 'DATNGUYEN'
  email: dongythaytoan123@gmail.com
  twitter_username: datnguyen12345
  facebook_username: datnguyen12345
  github_username: datnguyen12345
  #linkedin_username: ethan605
facebook:
  #app_id: 1783427568545702
  #admins: 1119670477
  #publisher: 1119670477
  #page: 275993682774772

# Build settings
destination: _site
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

gems:
  - github-pages
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
